/**
 * Hand-curated list behind src/data/software.ts: the software of oncology beyond what is open source, which product
 * belongs in which category, who sells it, and where to look for a source outside the company that names it.
 * scripts/fetch-software.ts reads this file, fetches what changes, and writes the data file. Nothing here is a fact
 * taken from the network; everything fetched is written by the script with the URL it came from.
 *
 * The sourcing rule this list exists to serve:
 *   - `url` is the company's own page. It establishes that the product exists, what it claims to do and where it
 *     lives. That is all it establishes. The script copies the page's own description into the record verbatim, as
 *     a claim attributed to the company, and records whether the page it fetched names the product at all.
 *   - `fda`, `paperQuery` and `listings` are the routes to a source outside the company. Each is fetched and each
 *     is checked to name the product before it is recorded. A record with none of them is "self-described" and the
 *     page says so in that row, rather than letting a company's own words pass for evidence.
 *
 * Open-source projects are not here. They are in scripts/open-source-curated.ts and on /open-source/. What is here
 * from that map is the part it excluded by design: research tools that are free or commercial but not open, Sentieon
 * among them, which now have a home with their evidence attached rather than only a line in a skip list.
 *
 * SKIPPED lists what was looked for and deliberately not recorded, with the reason, so the page can say so.
 */
import type { SoftwareCategory, SoftwareSegment } from "../src/lib/schema";

export type CuratedSoftware = {
  id: string;
  name: string;
  /** The company, institution or public body behind it, as free text. */
  vendor: string;
  /** A company or institution id in the corpus, when there is one; the script resolves the name from it. */
  vendorId?: string;
  category: SoftwareCategory;
  segment: SoftwareSegment;
  /** OnCo's plain-English gloss of what the product is. Never a claim about performance, adoption or clearance. */
  summary: string;
  /** The company's own page, fetched for the claim and to confirm the product exists. */
  url: string;
  /** The string the fetched page must contain for the record to count the page as naming the product; defaults to `name`. */
  pageMatch?: string;
  /**
   * An openFDA device query. `search` is the query as the API takes it; `applicant` and `device` are substrings every
   * returned record must contain (case-insensitive) before it is recorded, so a broad query cannot pull in another
   * company's device of the same name.
   */
  fda?: { endpoint: "510k" | "pma"; search: string; applicant?: string; device?: string };
  /** A Europe PMC query. Every hit must also contain `paperMatch` (default: the product name) in title or abstract. */
  paperQuery?: string;
  paperMatch?: string;
  /** Pages published by a body other than the vendor that name the product; each is fetched and checked for `match`. */
  listings?: Array<{ body: string; label: string; url: string; match: string }>;
  /** The id in src/data/open-source.ts when an open-source project is the same tool, its core, or its counterpart. */
  openSourceId?: string;
  technologies?: string[];
  cancers?: string[];
  note?: string;
};

const C = {
  clin: "clinical-systems",
  samd: "regulated-device",
  gen: "genomics-interpretation",
  trial: "trials-registries",
  case: "case-review",
  research: "research-analysis",
} as const satisfies Record<string, SoftwareCategory>;

const S = {
  ehr: "Oncology electronic record",
  chemo: "Chemotherapy prescribing",
  rtp: "Radiotherapy planning",
  rtqa: "Radiotherapy QA and dosimetry",
  pos: "Patient positioning and monitoring",
  pathPlat: "Pathology platform",
  radPlat: "Radiology platform",
  pathAi: "Pathology AI",
  radAi: "Radiology AI",
  scopeAi: "Endoscopy and dermatology AI",
  calling: "Sequencing and variant calling",
  interp: "Variant interpretation and reporting",
  cgp: "Comprehensive genomic profiling",
  registry: "Trial registry",
  matching: "Trial matching",
  conduct: "Trial conduct software",
  cancerReg: "Cancer registry software",
  rwd: "Real-world data platform",
  review: "Case review and second opinion",
  pro: "Patient-reported outcomes",
  risk: "Risk and decision tools",
  tool: "Research analysis tool",
} as const satisfies Record<string, SoftwareSegment>;

export const CURATED: CuratedSoftware[] = [
  // ─── Clinical systems: the oncology record and what prescribes from it ─────────────────────────────────────────
  {
    id: "aria-ois", name: "ARIA Oncology Information System", vendor: "Varian", vendorId: "varian", category: C.clin, segment: S.ehr,
    summary: "The oncology record and record-and-verify system that sits between a radiotherapy plan and the machine that delivers it, holding the prescription, the images, the schedule and the delivered dose.",
    url: "https://www.varian.com/products/software/digital-oncology/legacy-solutions/aria-oncology-information-system", pageMatch: "ARIA",
    fda: { endpoint: "510k", search: 'device_name:"ARIA"', applicant: "Varian" },
    paperQuery: 'TITLE:"ARIA oncology information system"', paperMatch: "ARIA",
    technologies: ["oncology-information-systems"],
  },
  {
    id: "aria-core", name: "ARIA CORE", vendor: "Varian", vendorId: "varian", category: C.clin, segment: S.ehr,
    summary: "The current generation of Varian's oncology management system, sold as the record layer across radiotherapy, systemic therapy and theranostics.",
    url: "https://www.varian.com/products/software/digital-oncology/oncology-management-systems/aria-core", pageMatch: "ARIA",
    technologies: ["oncology-information-systems"],
  },
  {
    id: "aria-systemic-therapy", name: "ARIA Systemic Therapy Management", vendor: "Varian", vendorId: "varian", category: C.clin, segment: S.chemo,
    summary: "The chemotherapy side of ARIA: regimen libraries, dose calculation and the prescribing and administration checks a day unit works through before a drug is given.",
    url: "https://www.varian.com/products/software/digital-oncology/oncology-management-systems/aria-systemic-therapy-management", pageMatch: "Systemic Therapy",
    technologies: ["oncology-information-systems", "hospital-information-systems-oncology"],
  },
  {
    id: "mosaiq", name: "MOSAIQ Oncology Information System", vendor: "Elekta", vendorId: "elekta", category: C.clin, segment: S.ehr,
    summary: "Elekta's oncology information system, the other half of the record-and-verify duopoly in radiotherapy departments, covering scheduling, prescription, delivery records and medical oncology.",
    url: "https://www.elekta.com/products/oncology-informatics/elekta-one/mosaiq-3/", pageMatch: "MOSAIQ",
    fda: { endpoint: "510k", search: 'device_name:"MOSAIQ"', applicant: "Elekta" },
    paperQuery: 'TITLE:"MOSAIQ" AND (radiotherapy OR radiation OR oncology)', paperMatch: "MOSAIQ",
    technologies: ["oncology-information-systems"],
  },
  {
    id: "elekta-one", name: "Elekta ONE", vendor: "Elekta", vendorId: "elekta", category: C.clin, segment: S.ehr,
    summary: "Elekta's bundle of planning, delivery and information software sold as one environment, with MOSAIQ as its record layer.",
    url: "https://www.elekta.com/products/oncology-informatics/elekta-one/", pageMatch: "Elekta ONE",
    technologies: ["oncology-information-systems", "adaptive-radiotherapy"],
  },
  {
    id: "raycare", name: "RayCare", vendor: "RaySearch Laboratories", vendorId: "raysearch", category: C.clin, segment: S.ehr,
    summary: "RaySearch's oncology information system, built to sit beside RayStation so planning and the record share one data model.",
    url: "https://www.raysearchlabs.com/raycare/", pageMatch: "RayCare",
    fda: { endpoint: "510k", search: 'applicant:"RaySearch Laboratories"', applicant: "RaySearch", device: "RayCare" },
    technologies: ["oncology-information-systems"],
  },
  {
    id: "epic-beacon", name: "Epic Beacon", vendor: "Epic Systems", vendorId: "epic-systems", category: C.clin, segment: S.chemo,
    summary: "The oncology module of the Epic electronic record: treatment plans, regimen libraries, chemotherapy ordering and the checks that run before a cycle is released.",
    url: "https://www.epic.com/software/oncology/", pageMatch: "oncology",
    paperQuery: 'TITLE:"Epic Beacon"', paperMatch: "Beacon",
    technologies: ["hospital-information-systems-oncology"],
  },
  {
    id: "meditech-expanse-oncology", name: "MEDITECH Expanse Oncology", vendor: "MEDITECH", category: C.clin, segment: S.chemo,
    summary: "The oncology module of the MEDITECH record, with regimen-based ordering and the administration record for systemic therapy.",
    url: "https://ehr.meditech.com/ehr-solutions/meditech-expanse-oncology", pageMatch: "Oncology",
    technologies: ["hospital-information-systems-oncology"],
  },
  {
    id: "oncoemr", name: "OncoEMR", vendor: "Flatiron Health", vendorId: "flatiron-health", category: C.clin, segment: S.ehr,
    summary: "An oncology-specific electronic record used by community practices in the United States, and the point of care that feeds Flatiron's real-world database.",
    url: "https://flatiron.com/", pageMatch: "OncoEMR",
    paperQuery: 'TITLE:"OncoEMR"', paperMatch: "OncoEMR",
    technologies: ["hospital-information-systems-oncology"],
  },
  {
    id: "chemocare", name: "ChemoCare", vendor: "CIS Oncology", category: C.clin, segment: S.chemo,
    summary: "A chemotherapy prescribing and management system used by NHS trusts: protocol libraries, dose banding, pharmacy verification and the administration record.",
    url: "https://www.cis-healthcare.com/", pageMatch: "ChemoCare",
    technologies: ["hospital-information-systems-oncology"],
  },
  {
    id: "civica-clinical-pathways", name: "Civica Clinical Pathways (formerly InfoFlex)", vendor: "Civica", category: C.clin, segment: S.ehr,
    summary: "The cancer multidisciplinary team and pathway management system many NHS trusts run beside their main record, used to track referrals, meetings and waiting-time targets.",
    url: "https://www.civica.com/en-gb/product-pages/infoflex/", pageMatch: "InfoFlex",
    technologies: ["multidisciplinary-tumour-board", "hospital-information-systems-oncology"],
  },
  {
    id: "clinicalpath", name: "ClinicalPath (formerly Via Oncology)", vendor: "Elsevier", category: C.clin, segment: S.chemo,
    summary: "A clinical pathways product that narrows the regimen choice at the point of ordering to a reviewed list, and reports how often clinicians go off it.",
    url: "https://www.elsevier.com/products/clinicalpath", pageMatch: "ClinicalPath",
    paperQuery: 'TITLE:"Via Oncology"', paperMatch: "Via Oncology",
    technologies: ["hospital-information-systems-oncology"],
  },
  {
    id: "navigating-care", name: "Navigating Care", vendor: "Navigating Cancer", category: C.clin, segment: S.pro,
    summary: "A patient portal and symptom-reporting layer bolted onto a practice's oncology record, with triage pathways for the answers that need a call back.",
    url: "https://www.navigatingcancer.com/", pageMatch: "Navigating Care",
    technologies: ["telemedicine-teleoncology"],
  },
  {
    id: "noona", name: "Noona", vendor: "Varian", vendorId: "varian", category: C.clin, segment: S.pro,
    summary: "A patient-reported outcome and symptom-tracking application for people on cancer treatment, feeding the answers back to the treating team.",
    url: "https://www.varian.com/products/software/patient-engagement/noona", pageMatch: "Noona",
    technologies: ["telemedicine-teleoncology"],
  },
  {
    id: "ontada", name: "Ontada (iKnowMed)", vendor: "McKesson", vendorId: "mckesson-us-oncology", category: C.clin, segment: S.rwd,
    summary: "McKesson's oncology data and technology arm, built around the iKnowMed practice record used across The US Oncology Network.",
    url: "https://www.ontada.com/", pageMatch: "Ontada",
    technologies: ["hospital-information-systems-oncology"],
  },
  {
    id: "sectra-pacs", name: "Sectra PACS (IDS7)", vendor: "Sectra", vendorId: "sectra", category: C.clin, segment: S.radPlat,
    summary: "The picture archiving and communication system a radiology department reads on, and in many hospitals the same viewer now used for digital pathology slides.",
    url: "https://sectra.com/medical/", pageMatch: "Sectra",
    fda: { endpoint: "510k", search: 'applicant:"Sectra"', applicant: "Sectra", device: "IDS7" },
    technologies: ["quantitative-imaging-biomarkers"],
  },
  {
    id: "syngo-carbon", name: "Syngo Carbon", vendor: "Siemens Healthineers", vendorId: "siemens-healthineers", category: C.clin, segment: S.radPlat,
    summary: "Siemens Healthineers' enterprise imaging and reading platform, the reporting environment around its scanners.",
    url: "https://www.siemens-healthineers.com/digital-health-solutions/syngo-carbon", pageMatch: "Syngo Carbon",
    fda: { endpoint: "510k", search: 'device_name:"syngo"', applicant: "Siemens" },
    technologies: ["medical-imaging-scanner-manufacturing"],
  },
  {
    id: "intelerad", name: "Intelerad enterprise imaging", vendor: "Intelerad Medical Systems", category: C.clin, segment: S.radPlat,
    summary: "An enterprise imaging and PACS suite used by imaging groups and hospital networks to store, distribute and read studies across sites.",
    url: "https://www.intelerad.com/en/", pageMatch: "Intelerad",
  },
  {
    id: "agfa-enterprise-imaging", name: "AGFA HealthCare Enterprise Imaging", vendor: "AGFA HealthCare", category: C.clin, segment: S.radPlat,
    summary: "An enterprise imaging platform covering radiology, cardiology and departmental image workflows in hospitals.",
    url: "https://www.agfahealthcare.com/", pageMatch: "Enterprise Imaging",
  },
  {
    id: "philips-intellisite", name: "Philips IntelliSite Pathology Solution", vendor: "Philips", vendorId: "philips", category: C.clin, segment: S.pathPlat,
    summary: "A whole-slide scanning and viewing system for histopathology, the first such system cleared in the United States for primary diagnosis.",
    url: "https://www.philips.co.uk/healthcare/resources/landing/digital-pathology", pageMatch: "pathology",
    fda: { endpoint: "510k", search: 'device_name:"IntelliSite"', applicant: "Philips" },
    technologies: ["digital-pathology-ai", "histopathology-ihc"],
  },
  {
    id: "aperio-gt-450-dx", name: "Aperio GT 450 DX", vendor: "Leica Biosystems", vendorId: "leica-biosystems", category: C.clin, segment: S.pathPlat,
    summary: "A high-throughput whole-slide scanner and its viewing software, sold for primary diagnosis in histopathology.",
    url: "https://www.leicabiosystems.com/us/digital-pathology/scan/aperio-gt-450-dx/", pageMatch: "Aperio",
    fda: { endpoint: "510k", search: 'device_name:"Aperio"', applicant: "Leica" },
    technologies: ["digital-pathology-ai", "histopathology-ihc"],
  },
  {
    id: "sectra-digital-pathology", name: "Sectra Digital Pathology Module", vendor: "Sectra", vendorId: "sectra", category: C.clin, segment: S.pathPlat,
    summary: "Slide viewing and case management inside the same workstation a hospital already uses for radiology, which is how several health systems went digital in pathology.",
    url: "https://sectra.com/medical/digital-pathology/", pageMatch: "pathology",
    fda: { endpoint: "510k", search: 'applicant:"Sectra"', applicant: "Sectra", device: "Pathology" },
    technologies: ["digital-pathology-ai"],
  },
  {
    id: "concentriq-dx", name: "Concentriq Dx", vendor: "Proscia", vendorId: "proscia", category: C.clin, segment: S.pathPlat,
    summary: "A digital pathology image management platform that laboratories run as the layer between scanners and the algorithms they buy.",
    url: "https://proscia.com/", pageMatch: "Concentriq",
    fda: { endpoint: "510k", search: 'device_name:"Concentriq"', applicant: "Proscia" },
    technologies: ["digital-pathology-ai"],
  },
  {
    id: "halo-ap-dx", name: "HALO AP Dx", vendor: "Indica Labs", vendorId: "indica-labs", category: C.clin, segment: S.pathPlat,
    summary: "A digital pathology case management and image analysis platform used in diagnostic laboratories and in research.",
    url: "https://indicalab.com/halo-ap/", pageMatch: "HALO AP",
    fda: { endpoint: "510k", search: 'device_name:"HALO AP"', applicant: "Indica" },
    technologies: ["digital-pathology-ai", "ai-pathology-scoring"],
  },
  {
    id: "visiopharm-oncotopix", name: "Oncotopix Discovery", vendor: "Visiopharm", category: C.clin, segment: S.pathAi,
    summary: "Quantitative image analysis for stained tissue sections, used to score markers such as HER2, Ki-67 and PD-L1 rather than eyeballing them.",
    url: "https://visiopharm.com/", pageMatch: "Visiopharm",
    paperQuery: 'TITLE:"Visiopharm" OR ABSTRACT:"Visiopharm"', paperMatch: "Visiopharm",
    technologies: ["ai-pathology-scoring", "histopathology-ihc"],
  },
  {
    id: "aiforia", name: "Aiforia Clinical and Create", vendor: "Aiforia Technologies", category: C.clin, segment: S.pathAi,
    summary: "A platform for training and running deep-learning models on whole-slide images, sold to laboratories that want to build their own scoring algorithms.",
    url: "https://www.aiforia.com/", pageMatch: "Aiforia",
    paperQuery: 'TITLE:"AIFORIA" OR ABSTRACT:"Aiforia"', paperMatch: "aiforia",
    technologies: ["ai-pathology-scoring", "digital-pathology-ai"],
  },
  {
    id: "mindpeak-breastihc", name: "Mindpeak BreastIHC", vendor: "Mindpeak", category: C.clin, segment: S.pathAi,
    summary: "Algorithms that score immunohistochemistry on breast slides, sold to run inside the laboratory's existing viewer.",
    url: "https://mindpeak.ai/", pageMatch: "Mindpeak",
    paperQuery: 'ABSTRACT:"Mindpeak"', paperMatch: "Mindpeak",
    technologies: ["ai-pathology-scoring"], cancers: ["breast-cancer"],
  },
  {
    id: "deepdx-prostate", name: "DeepDx Prostate", vendor: "Deep Bio", category: C.clin, segment: S.pathAi,
    summary: "An algorithm that grades prostate biopsy slides, reporting Gleason patterns and tumour extent for a pathologist to confirm.",
    url: "https://www.deepbio.co.kr/", pageMatch: "Deep Bio",
    paperQuery: 'ABSTRACT:"DeepDx"', paperMatch: "DeepDx",
    technologies: ["ai-pathology-scoring"], cancers: ["prostate"],
  },

  // ─── Regulated software as a medical device: the clearances are the point ──────────────────────────────────────
  {
    id: "paige-prostate",
    listings: [{ body: "FDA", label: "Named in the FDA's published list of artificial-intelligence-enabled medical devices", url: "https://www.fda.gov/medical-devices/software-medical-device-samd/artificial-intelligence-enabled-medical-devices", match: "Paige Prostate" }],
    name: "Paige Prostate", vendor: "Paige AI", vendorId: "paige", category: C.samd, segment: S.pathAi,
    summary: "An algorithm that flags areas suspicious for prostate cancer on a scanned biopsy slide, the first such pathology algorithm authorised in the United States.",
    url: "https://www.paige.ai/", pageMatch: "Paige",
    fda: { endpoint: "510k", search: 'applicant:"Paige.AI"', applicant: "Paige" },
    paperQuery: 'TITLE:"Paige Prostate"', paperMatch: "Paige Prostate",
    technologies: ["ai-pathology-scoring", "pathology-foundation-model"], cancers: ["prostate"],
  },
  {
    id: "galen-second-read", name: "Galen Second Read", vendor: "Ibex Medical Analytics", vendorId: "ibex-medical-analytics", category: C.samd, segment: S.pathAi,
    summary: "A second-read algorithm over scanned biopsy slides that marks cases the laboratory should look at again before the report goes out.",
    url: "https://ibex-ai.com/", pageMatch: "Galen",
    fda: { endpoint: "510k", search: 'applicant:"Ibex"', applicant: "Ibex" },
    technologies: ["ai-pathology-scoring"],
  },
  {
    id: "aisight-dx", name: "AISight Dx", vendor: "PathAI", vendorId: "pathai", category: C.samd, segment: S.pathPlat,
    summary: "PathAI's image management system for diagnostic laboratories, the platform its algorithms are meant to run inside.",
    url: "https://www.pathai.com/", pageMatch: "AISight",
    fda: { endpoint: "510k", search: 'device_name:"AISight"', applicant: "PathAI" },
    technologies: ["digital-pathology-ai", "pathology-foundation-model"],
  },
  {
    id: "msintuit-crc", name: "MSIntuit CRC", vendor: "Owkin", vendorId: "owkin", category: C.samd, segment: S.pathAi,
    summary: "A pre-screening algorithm that reads a routine colorectal slide and rules out the cases unlikely to be microsatellite unstable, so fewer go for molecular testing.",
    url: "https://www.owkin.com/diagnostics/msintuit-crc", pageMatch: "MSIntuit",
    paperQuery: 'TITLE:"MSIntuit"', paperMatch: "MSIntuit",
    technologies: ["ai-pathology-scoring"], cancers: ["colorectal"],
  },
  {
    id: "transpara",
    listings: [{ body: "FDA", label: "Named in the FDA's published list of artificial-intelligence-enabled medical devices", url: "https://www.fda.gov/medical-devices/software-medical-device-samd/artificial-intelligence-enabled-medical-devices", match: "Transpara" }],
    name: "Transpara", vendor: "ScreenPoint Medical", vendorId: "screenpoint-medical", category: C.samd, segment: S.radAi,
    summary: "A mammography reading algorithm used in screening programmes, scoring each examination and marking suspicious findings for the reader.",
    url: "https://screenpoint-medical.com/", pageMatch: "Transpara",
    fda: { endpoint: "510k", search: 'device_name:"Transpara"', applicant: "Screenpoint" },
    paperQuery: 'TITLE:"Transpara" OR ABSTRACT:"Transpara"', paperMatch: "Transpara",
    technologies: ["radiology-ai-screening"], cancers: ["breast-cancer"],
  },
  {
    id: "profound-ai",
    listings: [{ body: "FDA", label: "Named in the FDA's published list of artificial-intelligence-enabled medical devices", url: "https://www.fda.gov/medical-devices/software-medical-device-samd/artificial-intelligence-enabled-medical-devices", match: "ProFound AI" }],
    name: "ProFound AI", vendor: "iCAD", vendorId: "icad", category: C.samd, segment: S.radAi,
    summary: "Detection and density software for digital breast tomosynthesis and mammography, marking lesions and giving a case score.",
    url: "https://www.icadmed.com/profoundai.html", pageMatch: "ProFound AI",
    fda: { endpoint: "510k", search: 'applicant:"iCAD"', applicant: "iCAD", device: "ProFound" },
    paperQuery: 'ABSTRACT:"ProFound AI"', paperMatch: "ProFound AI",
    technologies: ["radiology-ai-screening"], cancers: ["breast-cancer"],
  },
  {
    id: "genius-ai-detection",
    listings: [{ body: "FDA", label: "Named in the FDA's published list of artificial-intelligence-enabled medical devices", url: "https://www.fda.gov/medical-devices/software-medical-device-samd/artificial-intelligence-enabled-medical-devices", match: "Genius AI" }],
    name: "Genius AI Detection", vendor: "Hologic", vendorId: "hologic", category: C.samd, segment: S.radAi,
    summary: "Hologic's detection algorithm for its own tomosynthesis systems, marking lesions and ranking cases for the reader.",
    url: "https://www.hologic.com/", pageMatch: "Genius",
    fda: { endpoint: "510k", search: 'device_name:"Genius AI"', applicant: "Hologic" },
    technologies: ["radiology-ai-screening"], cancers: ["breast-cancer"],
  },
  {
    id: "mammoscreen",
    listings: [{ body: "FDA", label: "Named in the FDA's published list of artificial-intelligence-enabled medical devices", url: "https://www.fda.gov/medical-devices/software-medical-device-samd/artificial-intelligence-enabled-medical-devices", match: "MammoScreen" }],
    name: "MammoScreen", vendor: "Therapixel", vendorId: "therapixel", category: C.samd, segment: S.radAi,
    summary: "A mammography reading algorithm that scores each breast and marks findings, with a separate density product.",
    url: "https://www.therapixel.com/", pageMatch: "MammoScreen",
    fda: { endpoint: "510k", search: 'device_name:"MammoScreen"', applicant: "Therapixel" },
    paperQuery: 'TITLE:"MammoScreen"', paperMatch: "MammoScreen",
    technologies: ["radiology-ai-screening"], cancers: ["breast-cancer"],
  },
  {
    id: "lunit-insight-mmg",
    listings: [{ body: "FDA", label: "Named in the FDA's published list of artificial-intelligence-enabled medical devices", url: "https://www.fda.gov/medical-devices/software-medical-device-samd/artificial-intelligence-enabled-medical-devices", match: "Lunit INSIGHT MMG" }],
    name: "Lunit INSIGHT", vendor: "Lunit", vendorId: "lunit", category: C.samd, segment: S.radAi,
    summary: "A family of reading algorithms sold into screening and diagnostic imaging: mammography, tomosynthesis and chest radiographs, each cleared separately.",
    url: "https://www.lunit.io/en/products/mmg", pageMatch: "Lunit INSIGHT",
    fda: { endpoint: "510k", search: 'applicant:"Lunit"', applicant: "Lunit" },
    paperQuery: 'TITLE:"Lunit INSIGHT"', paperMatch: "Lunit INSIGHT",
    technologies: ["radiology-ai-screening"], cancers: ["breast-cancer"],
  },
  {
    id: "lunit-scope", name: "Lunit SCOPE", vendor: "Lunit", vendorId: "lunit", category: C.samd, segment: S.pathAi,
    summary: "Lunit's pathology side: algorithms that read stained slides for PD-L1 expression and for the immune phenotype of the tumour microenvironment.",
    url: "https://www.lunit.io/en/products/scope", pageMatch: "SCOPE",
    paperQuery: 'TITLE:"Lunit SCOPE"', paperMatch: "Lunit SCOPE",
    technologies: ["ai-pathology-scoring"],
  },
  {
    id: "saige-dx",
    listings: [{ body: "FDA", label: "Named in the FDA's published list of artificial-intelligence-enabled medical devices", url: "https://www.fda.gov/medical-devices/software-medical-device-samd/artificial-intelligence-enabled-medical-devices", match: "Saige-Dx" }],
    name: "Saige-Dx", vendor: "DeepHealth (RadNet)", category: C.samd, segment: S.radAi,
    summary: "A mammography reading algorithm from RadNet's software arm, with triage and density products alongside it.",
    url: "https://www.deephealth.com/", pageMatch: "Saige",
    fda: { endpoint: "510k", search: 'applicant:"DeepHealth"', applicant: "DeepHealth" },
    technologies: ["radiology-ai-screening"], cancers: ["breast-cancer"],
  },
  {
    id: "volpara-imaging",
    listings: [{ body: "FDA", label: "Named in the FDA's published list of artificial-intelligence-enabled medical devices", url: "https://www.fda.gov/medical-devices/software-medical-device-samd/artificial-intelligence-enabled-medical-devices", match: "Volpara" }],
    name: "Volpara Imaging Software", vendor: "Volpara Health", vendorId: "volpara-health", category: C.samd, segment: S.radAi,
    summary: "Software that measures breast density and image quality from mammograms, used to drive supplemental screening pathways.",
    url: "https://www.volparahealth.com/", pageMatch: "Volpara",
    fda: { endpoint: "510k", search: 'applicant:"Volpara"', applicant: "Volpara" },
    technologies: ["radiology-ai-screening"], cancers: ["breast-cancer"],
  },
  {
    id: "briefcase-aidoc",
    listings: [{ body: "FDA", label: "Named in the FDA's published list of artificial-intelligence-enabled medical devices", url: "https://www.fda.gov/medical-devices/software-medical-device-samd/artificial-intelligence-enabled-medical-devices", match: "BriefCase" }],
    name: "BriefCase", vendor: "Aidoc", vendorId: "aidoc", category: C.samd, segment: S.radAi,
    summary: "Aidoc's family of triage algorithms that push suspected findings on CT to the top of a radiologist's worklist, including incidental findings that matter in cancer care.",
    url: "https://www.aidoc.com/", pageMatch: "Aidoc",
    fda: { endpoint: "510k", search: 'applicant:"Aidoc"', applicant: "Aidoc" },
    technologies: ["radiology-ai-screening", "aidoc-care"],
  },
  {
    id: "optellum-vnc",
    listings: [{ body: "FDA", label: "Named in the FDA's published list of artificial-intelligence-enabled medical devices", url: "https://www.fda.gov/medical-devices/software-medical-device-samd/artificial-intelligence-enabled-medical-devices", match: "Optellum" }],
    name: "Optellum Virtual Nodule Clinic", vendor: "Optellum", vendorId: "optellum", category: C.samd, segment: S.radAi,
    summary: "Software that scores the malignancy risk of a lung nodule seen on CT and tracks it over time, aimed at the decision of whether to biopsy.",
    url: "https://optellum.com/", pageMatch: "Optellum",
    fda: { endpoint: "510k", search: 'device_name:"Optellum"', applicant: "Optellum" },
    paperQuery: 'ABSTRACT:"Optellum"', paperMatch: "Optellum",
    technologies: ["radiology-ai-screening"], cancers: ["lung-cancer"],
  },
  {
    id: "clearread-ct",
    listings: [{ body: "FDA", label: "Named in the FDA's published list of artificial-intelligence-enabled medical devices", url: "https://www.fda.gov/medical-devices/software-medical-device-samd/artificial-intelligence-enabled-medical-devices", match: "ClearRead" }],
    name: "ClearRead CT", vendor: "Riverain Technologies", category: C.samd, segment: S.radAi,
    summary: "Software that suppresses vessels on chest CT so nodules stand out, with a detection algorithm on top.",
    url: "https://www.riveraintech.com/", pageMatch: "ClearRead",
    fda: { endpoint: "510k", search: 'applicant:"Riverain"', applicant: "Riverain", device: "ClearRead" },
    paperQuery: 'ABSTRACT:"ClearRead"', paperMatch: "ClearRead",
    technologies: ["radiology-ai-screening"], cancers: ["lung-cancer"],
  },
  {
    id: "qxr-ln",
    listings: [{ body: "FDA", label: "Named in the FDA's published list of artificial-intelligence-enabled medical devices", url: "https://www.fda.gov/medical-devices/software-medical-device-samd/artificial-intelligence-enabled-medical-devices", match: "qXR" }],
    name: "qXR", vendor: "Qure.ai", category: C.samd, segment: S.radAi,
    summary: "A family of chest radiograph and CT algorithms that flag lung nodules and other findings, deployed in screening and case-finding programmes in several countries.",
    url: "https://qure.ai/", pageMatch: "qXR",
    fda: { endpoint: "510k", search: 'applicant:"Qure.ai"', applicant: "Qure" },
    paperQuery: 'TITLE:"qXR" AND (nodule OR chest OR lung OR tuberculosis)', paperMatch: "qXR",
    technologies: ["radiology-ai-screening"], cancers: ["lung-cancer"],
  },
  {
    id: "annalise-enterprise",
    listings: [{ body: "FDA", label: "Named in the FDA's published list of artificial-intelligence-enabled medical devices", url: "https://www.fda.gov/medical-devices/software-medical-device-samd/artificial-intelligence-enabled-medical-devices", match: "Annalise" }],
    name: "Annalise Enterprise CXR", vendor: "Annalise.ai (harrison.ai)", category: C.samd, segment: S.radAi,
    summary: "A chest radiograph algorithm that reports many findings at once and triages the urgent ones, including masses and nodules.",
    url: "https://www.annalise.ai/", pageMatch: "Annalise",
    fda: { endpoint: "510k", search: 'applicant:"Annalise"', applicant: "Annalise" },
    technologies: ["radiology-ai-screening"],
  },
  {
    id: "ai-rad-companion",
    listings: [{ body: "FDA", label: "Named in the FDA's published list of artificial-intelligence-enabled medical devices", url: "https://www.fda.gov/medical-devices/software-medical-device-samd/artificial-intelligence-enabled-medical-devices", match: "AI-Rad Companion" }],
    name: "AI-Rad Companion", vendor: "Siemens Healthineers", vendorId: "siemens-healthineers", category: C.samd, segment: S.radAi,
    summary: "A family of reading algorithms for CT and MR, including organ contouring for radiotherapy and prostate MR reading.",
    url: "https://www.siemens-healthineers.com/digital-health-solutions/ai-rad-companion", pageMatch: "AI-Rad Companion",
    fda: { endpoint: "510k", search: 'device_name:"AI-Rad Companion"', applicant: "Siemens" },
    technologies: ["radiology-ai-screening", "auto-contouring-ai"],
  },
  {
    id: "gi-genius",
    listings: [{ body: "FDA", label: "Named in the FDA's published list of artificial-intelligence-enabled medical devices", url: "https://www.fda.gov/medical-devices/software-medical-device-samd/artificial-intelligence-enabled-medical-devices", match: "GI Genius" }],
    name: "GI Genius", vendor: "Cosmo Artificial Intelligence, distributed by Medtronic", vendorId: "medtronic", category: C.samd, segment: S.scopeAi,
    summary: "A module that watches the colonoscopy video in real time and boxes possible polyps, the first computer-aided detection device of its kind authorised in the United States.",
    url: "https://www.medtronic.com/covidien/en-us/products/gastrointestinal-artificial-intelligence/gi-genius-intelligent-endoscopy.html", pageMatch: "GI Genius",
    fda: { endpoint: "510k", search: 'device_name:"GI Genius"', applicant: "Cosmo" },
    paperQuery: 'TITLE:"GI Genius"', paperMatch: "GI Genius",
    technologies: ["ai-endoscopy-detection"], cancers: ["colorectal"],
  },
  {
    id: "endo-aid", name: "ENDO-AID CADe", vendor: "Olympus", vendorId: "olympus", category: C.samd, segment: S.scopeAi,
    summary: "Olympus's computer-aided detection module for its endoscopy processors, marking possible lesions during the examination.",
    url: "https://www.olympus-europa.com/medical/en/Products-and-Solutions/Products/Product/ENDO-AID.html", pageMatch: "ENDO-AID",
    paperQuery: 'TITLE:"ENDO-AID" OR ABSTRACT:"ENDO-AID"', paperMatch: "ENDO-AID",
    technologies: ["ai-endoscopy-detection"], cancers: ["colorectal"],
  },
  {
    id: "dermasensor",
    listings: [{ body: "FDA", label: "Named in the FDA's published list of artificial-intelligence-enabled medical devices", url: "https://www.fda.gov/medical-devices/software-medical-device-samd/artificial-intelligence-enabled-medical-devices", match: "DermaSensor" }],
    name: "DermaSensor", vendor: "DermaSensor", category: C.samd, segment: S.scopeAi,
    summary: "A handheld spectroscopy device with an algorithm that tells a primary care clinician whether a skin lesion should be referred.",
    url: "https://www.dermasensor.com/", pageMatch: "DermaSensor",
    fda: { endpoint: "510k", search: 'applicant:"DermaSensor"', applicant: "DermaSensor" },
    technologies: ["dermoscopy-ai"], cancers: ["melanoma"],
  },
  {
    id: "nevisense", name: "Nevisense", vendor: "SciBase", category: C.samd, segment: S.scopeAi,
    summary: "An electrical impedance spectroscopy device with a classifier that scores a suspicious skin lesion before the decision to excise.",
    url: "https://scibase.com/", pageMatch: "Nevisense",
    paperQuery: 'TITLE:"Nevisense"', paperMatch: "Nevisense",
    technologies: ["dermoscopy-ai", "confocal-oct-skin-imaging"], cancers: ["melanoma"],
  },
  {
    id: "skinvision", name: "SkinVision", vendor: "SkinVision", category: C.samd, segment: S.scopeAi,
    summary: "A smartphone application that assesses a photograph of a skin lesion and tells the user whether to see a doctor.",
    url: "https://www.skinvision.com/", pageMatch: "SkinVision",
    paperQuery: 'TITLE:"SkinVision"', paperMatch: "SkinVision",
    technologies: ["dermoscopy-ai"], cancers: ["melanoma"],
  },
  {
    id: "qp-prostate",
    listings: [{ body: "FDA", label: "Named in the FDA's published list of artificial-intelligence-enabled medical devices", url: "https://www.fda.gov/medical-devices/software-medical-device-samd/artificial-intelligence-enabled-medical-devices", match: "QP-Prostate" }],
    name: "QP-Prostate CAD", vendor: "Quibim", category: C.samd, segment: S.radAi,
    summary: "Software that segments the prostate on MR and highlights areas suspicious for clinically significant cancer.",
    url: "https://www.quibim.com/", pageMatch: "Quibim",
    fda: { endpoint: "510k", search: 'applicant:"Quibim"', applicant: "Quibim" },
    technologies: ["radiology-ai-screening", "quantitative-imaging-biomarkers"], cancers: ["prostate"],
  },
  {
    id: "lucida-prostate-core", name: "Prostate Core", vendor: "Lucida Medical", category: C.samd, segment: S.radAi,
    summary: "A prostate MR reading product from a Cambridge company, segmenting the gland and scoring suspicious areas.",
    url: "https://lucidamedical.com/", pageMatch: "Lucida",
    fda: { endpoint: "510k", search: 'device_name:"Prostate Core"', applicant: "Lucida" },
    technologies: ["radiology-ai-screening"], cancers: ["prostate"],
  },
  {
    id: "eyonis-lcs",
    listings: [{ body: "FDA", label: "Named in the FDA's published list of artificial-intelligence-enabled medical devices", url: "https://www.fda.gov/medical-devices/software-medical-device-samd/artificial-intelligence-enabled-medical-devices", match: "eyonis" }],
    name: "eyonis LCS", vendor: "Median Technologies", category: C.samd, segment: S.radAi,
    summary: "A lung cancer screening product that classifies nodules found on low-dose CT.",
    url: "https://www.mediantechnologies.com/", pageMatch: "eyonis",
    fda: { endpoint: "510k", search: 'applicant:"Median Technologies"', applicant: "Median" },
    technologies: ["radiology-ai-screening"], cancers: ["lung-cancer"],
  },
  {
    id: "subtlemr",
    listings: [{ body: "FDA", label: "Named in the FDA's published list of artificial-intelligence-enabled medical devices", url: "https://www.fda.gov/medical-devices/software-medical-device-samd/artificial-intelligence-enabled-medical-devices", match: "SubtleMR" }],
    name: "SubtleMR and SubtlePET", vendor: "Subtle Medical", category: C.samd, segment: S.radAi,
    summary: "Image enhancement software that lets MR and PET studies be acquired faster or at lower dose and reconstructed to diagnostic quality.",
    url: "https://subtlemedical.com/", pageMatch: "Subtle",
    fda: { endpoint: "510k", search: 'applicant:"Subtle Medical"', applicant: "Subtle" },
    technologies: ["medical-imaging-scanner-manufacturing"],
  },

  // ─── Radiotherapy planning, quality assurance and positioning ──────────────────────────────────────────────────
  {
    id: "raystation", name: "RayStation", vendor: "RaySearch Laboratories", vendorId: "raysearch", category: C.clin, segment: S.rtp,
    summary: "A treatment planning system for photons, protons and ions, with deep-learning segmentation and planning built in and a large physics literature behind it.",
    url: "https://www.raysearchlabs.com/raystation/", pageMatch: "RayStation",
    fda: { endpoint: "510k", search: 'applicant:"RaySearch Laboratories"', applicant: "RaySearch", device: "RayStation" },
    paperQuery: 'TITLE:"RayStation"', paperMatch: "RayStation",
    technologies: ["treatment-planning-systems", "auto-contouring-ai"],
  },
  {
    id: "eclipse", name: "Eclipse", vendor: "Varian", vendorId: "varian", category: C.clin, segment: S.rtp,
    summary: "Varian's treatment planning system, the one most photon plans in the world are optimised and calculated in.",
    url: "https://www.varian.com/products/radiotherapy/treatment-planning/eclipse", pageMatch: "Eclipse",
    paperQuery: 'TITLE:"Eclipse treatment planning"', paperMatch: "Eclipse",
    technologies: ["treatment-planning-systems"],
  },
  {
    id: "monaco", name: "Monaco", vendor: "Elekta", vendorId: "elekta", category: C.clin, segment: S.rtp,
    summary: "Elekta's treatment planning system, with a Monte Carlo dose engine and the planning side of its MR-guided systems.",
    url: "https://www.elekta.com/products/radiation-therapy/monaco/", pageMatch: "Monaco",
    fda: { endpoint: "510k", search: 'device_name:"Monaco"', applicant: "Elekta" },
    paperQuery: 'TITLE:"Monaco treatment planning"', paperMatch: "Monaco",
    technologies: ["treatment-planning-systems"],
  },
  {
    id: "ethos", name: "Ethos Treatment Management", vendor: "Varian", vendorId: "varian", category: C.clin, segment: S.rtp,
    summary: "The planning and adaptation software behind online adaptive radiotherapy, which re-plans on the day's image while the patient is on the couch.",
    url: "https://www.varian.com/products/adaptive-therapy/ethos", pageMatch: "Ethos",
    fda: { endpoint: "510k", search: 'device_name:"Ethos"', applicant: "Varian" },
    technologies: ["adaptive-radiotherapy", "auto-contouring-ai", "in-room-imaging-systems"],
  },
  {
    id: "velocity", name: "Velocity", vendor: "Varian", vendorId: "varian", category: C.clin, segment: S.rtp,
    summary: "Image registration and dose accumulation software used to bring prior imaging and prior dose into a new plan.",
    url: "https://www.varian.com/products/software/treatment-planning/velocity", pageMatch: "Velocity",
    technologies: ["treatment-planning-systems", "adaptive-radiotherapy"],
  },
  {
    id: "accuray-precision", name: "Accuray Precision", vendor: "Accuray", vendorId: "accuray", category: C.clin, segment: S.rtp,
    summary: "The planning system for CyberKnife and TomoTherapy delivery, including the tracking models those machines plan around.",
    url: "https://www.accuray.com/software/", pageMatch: "Precision",
    fda: { endpoint: "510k", search: 'applicant:"Accuray"', applicant: "Accuray", device: "Precision" },
    technologies: ["treatment-planning-systems"],
  },
  {
    id: "brainlab-elements", name: "Brainlab Elements", vendor: "Brainlab", vendorId: "brainlab", category: C.clin, segment: S.rtp,
    summary: "A modular planning suite for cranial radiosurgery and stereotactic treatment, including automatic segmentation and multiple-metastasis planning.",
    url: "https://www.brainlab.com/radiosurgery-products/elements/", pageMatch: "Elements",
    fda: { endpoint: "510k", search: 'applicant:"Brainlab"', applicant: "Brainlab", device: "Element" },
    technologies: ["treatment-planning-systems", "auto-contouring-ai"],
  },
  {
    id: "leksell-gammaplan", name: "Leksell GammaPlan", vendor: "Elekta", vendorId: "elekta", category: C.clin, segment: S.rtp,
    summary: "The planning system for Gamma Knife radiosurgery, where the plan is a set of shots rather than a set of beams.",
    url: "https://www.elekta.com/products/oncology-informatics/", pageMatch: "Elekta",
    fda: { endpoint: "510k", search: 'applicant:"Elekta Instrument AB"', applicant: "Elekta", device: "GammaPlan" },
    technologies: ["treatment-planning-systems"],
  },
  {
    id: "oncentra-brachy", name: "Oncentra Brachy", vendor: "Elekta", vendorId: "elekta", category: C.clin, segment: S.rtp,
    summary: "The planning system for high-dose-rate brachytherapy, where the dose is planned around the applicator inside the patient.",
    url: "https://www.elekta.com/products/brachytherapy/oncentra-brachy/", pageMatch: "Oncentra",
    fda: { endpoint: "510k", search: 'device_name:"Oncentra"', device: "Oncentra" },
    technologies: ["treatment-planning-systems"],
  },
  {
    id: "mim-maestro", name: "MIM Maestro", vendor: "MIM Software", vendorId: "mim-software", category: C.clin, segment: S.rtp,
    summary: "Contouring, registration and dosimetry software used across radiation oncology and nuclear medicine, including dosimetry for radioligand therapy.",
    url: "https://www.mimsoftware.com/solutions/radiation-oncology", pageMatch: "MIM",
    fda: { endpoint: "510k", search: 'applicant:"MIM Software"', applicant: "MIM" },
    technologies: ["treatment-planning-systems", "auto-contouring-ai"],
  },
  {
    id: "mirada-rtx", name: "Mirada RTx and DLCExpert", vendor: "Mirada Medical", category: C.clin, segment: S.rtp,
    summary: "Deformable registration and deep-learning contouring for radiotherapy planning, from an Oxford company.",
    url: "https://mirada-medical.com/", pageMatch: "Mirada",
    fda: { endpoint: "510k", search: 'applicant:"Mirada Medical"', applicant: "Mirada" },
    technologies: ["auto-contouring-ai", "treatment-planning-systems"],
  },
  {
    id: "limbus-contour",
    listings: [{ body: "FDA", label: "Named in the FDA's published list of artificial-intelligence-enabled medical devices", url: "https://www.fda.gov/medical-devices/software-medical-device-samd/artificial-intelligence-enabled-medical-devices", match: "Limbus Contour" }],
    name: "Limbus Contour", vendor: "Limbus AI", vendorId: "limbus-ai", category: C.clin, segment: S.rtp,
    summary: "Automatic organ-at-risk contouring for radiotherapy planning, sold as a step that runs before the planner opens the case.",
    url: "https://limbus.ai/", pageMatch: "Limbus",
    fda: { endpoint: "510k", search: 'device_name:"Limbus Contour"', applicant: "Limbus" },
    technologies: ["auto-contouring-ai"],
  },
  {
    id: "contour-protege-ai",
    listings: [{ body: "FDA", label: "Named in the FDA's published list of artificial-intelligence-enabled medical devices", url: "https://www.fda.gov/medical-devices/software-medical-device-samd/artificial-intelligence-enabled-medical-devices", match: "Contour Proteg" }],
    name: "Contour ProtegeAI", vendor: "MIM Software", vendorId: "mim-software", category: C.clin, segment: S.rtp,
    summary: "MIM's deep-learning contouring product, cleared separately from the rest of the suite.",
    url: "https://www.mimsoftware.com/", pageMatch: "MIM",
    fda: { endpoint: "510k", search: 'applicant:"MIM Software"', applicant: "MIM", device: "Contour" },
    technologies: ["auto-contouring-ai"],
  },
  {
    id: "autocontour",
    listings: [{ body: "FDA", label: "Named in the FDA's published list of artificial-intelligence-enabled medical devices", url: "https://www.fda.gov/medical-devices/software-medical-device-samd/artificial-intelligence-enabled-medical-devices", match: "AutoContour" }],
    name: "AutoContour", vendor: "Radformation", vendorId: "radformation", category: C.clin, segment: S.rtp,
    summary: "Automatic contouring sold alongside a set of plan checking tools, aimed at the time a physicist spends on routine work.",
    url: "https://radformation.com/", pageMatch: "AutoContour",
    fda: { endpoint: "510k", search: 'applicant:"Radformation"', applicant: "Radformation", device: "AutoContour" },
    technologies: ["auto-contouring-ai"],
  },
  {
    id: "clearcheck", name: "ClearCheck and ChartCheck", vendor: "Radformation", vendorId: "radformation", category: C.clin, segment: S.rtqa,
    summary: "Plan evaluation and chart checking software that runs a department's own constraint list against every plan before it is approved.",
    url: "https://radformation.com/", pageMatch: "ClearCheck",
    fda: { endpoint: "510k", search: 'applicant:"Radformation"', applicant: "Radformation", device: "Check" },
    technologies: ["treatment-planning-systems"],
  },
  {
    id: "suncheck", name: "SunCHECK", vendor: "Sun Nuclear", vendorId: "sun-nuclear", category: C.clin, segment: S.rtqa,
    summary: "A quality assurance platform that checks both the machine and the patient plan, replacing a shelf of separate measurement tools.",
    url: "https://www.sunnuclear.com/", pageMatch: "SunCHECK",
    fda: { endpoint: "510k", search: 'applicant:"Sun Nuclear"', applicant: "Sun Nuclear", device: "SunCHECK" },
    paperQuery: 'TITLE:"SunCHECK" AND (dosimetry OR "quality assurance" OR radiotherapy)', paperMatch: "SunCHECK",
    technologies: ["treatment-planning-systems"],
  },
  {
    id: "delta4", name: "Delta4", vendor: "ScandiDos", category: C.clin, segment: S.rtqa,
    summary: "A measuring phantom and its software for verifying that a delivered plan matches the planned dose, and a version that checks it without a phantom.",
    url: "https://scandidos.com/", pageMatch: "Delta4",
    fda: { endpoint: "510k", search: 'applicant:"ScandiDos"', applicant: "ScandiDos" },
    paperQuery: 'TITLE:"Delta4" AND (IMRT OR VMAT OR dosimetry OR verification)', paperMatch: "Delta4",
    technologies: ["treatment-planning-systems"],
  },
  {
    id: "ptw-beamscan", name: "BEAMSCAN and OCTAVIUS", vendor: "PTW Freiburg", vendorId: "ptw-freiburg", category: C.clin, segment: S.rtqa,
    summary: "Water phantom scanning and array measurement systems with the software that commissions a linear accelerator and checks it afterwards.",
    url: "https://www.ptwdosimetry.com/", pageMatch: "PTW",
    fda: { endpoint: "510k", search: 'applicant:"PTW"', applicant: "PTW" },
    technologies: ["treatment-planning-systems"],
  },
  {
    id: "standard-imaging-qa", name: "DoseView and PIPSpro", vendor: "Standard Imaging", vendorId: "standard-imaging", category: C.clin, segment: S.rtqa,
    summary: "Dosimetry instruments and the quality assurance software that goes with them, including brachytherapy well chambers.",
    url: "https://www.standardimaging.com/", pageMatch: "Standard Imaging",
    fda: { endpoint: "510k", search: 'applicant:"Standard Imaging"', applicant: "Standard Imaging" },
    technologies: ["treatment-planning-systems"],
  },
  {
    id: "alignrt", name: "AlignRT", vendor: "Vision RT", vendorId: "vision-rt", category: C.clin, segment: S.pos,
    summary: "Surface-guided radiotherapy: cameras watch the skin surface and hold the beam if the patient moves, which is how breath-hold breast treatment is delivered without tattoos.",
    url: "https://www.visionrt.com/", pageMatch: "AlignRT",
    fda: { endpoint: "510k", search: 'applicant:"Vision RT"', applicant: "Vision RT" },
    paperQuery: 'TITLE:"AlignRT"', paperMatch: "AlignRT",
    technologies: ["in-room-imaging-systems"], cancers: ["breast-cancer"],
  },
  {
    id: "catalyst-crad", name: "Catalyst and Sentinel", vendor: "C-RAD", vendorId: "c-rad", category: C.clin, segment: S.pos,
    summary: "Optical surface scanning and respiratory gating systems for positioning and monitoring a patient during treatment.",
    url: "https://c-rad.com/", pageMatch: "C-RAD",
    fda: { endpoint: "510k", search: 'applicant:"C-RAD"', applicant: "C-RAD" },
    technologies: ["in-room-imaging-systems"],
  },

  // ─── Genomics and interpretation ───────────────────────────────────────────────────────────────────────────────
  {
    id: "foundationone-cdx", name: "FoundationOne CDx", vendor: "Foundation Medicine", vendorId: "foundation-medicine", category: C.gen, segment: S.cgp,
    summary: "A comprehensive genomic profiling test and the report software around it, approved as a companion diagnostic for a long and growing list of drugs.",
    url: "https://www.foundationmedicine.com/test/foundationone-cdx", pageMatch: "FoundationOne",
    fda: { endpoint: "pma", search: 'applicant:"Foundation Medicine"', applicant: "Foundation Medicine", device: "FoundationOne CDx" },
    paperQuery: 'TITLE:"FoundationOne CDx"', paperMatch: "FoundationOne",
    technologies: ["cgp", "variant-knowledgebases"],
  },
  {
    id: "guardant360-cdx", name: "Guardant360 CDx", vendor: "Guardant Health", vendorId: "guardant-health", category: C.gen, segment: S.cgp,
    summary: "A blood-based genomic profiling test with the reporting and companion-diagnostic claims that let a result choose a drug without a tissue biopsy.",
    url: "https://guardanthealth.com/", pageMatch: "Guardant360",
    fda: { endpoint: "pma", search: 'applicant:"Guardant Health"', applicant: "Guardant", device: "Guardant360" },
    paperQuery: 'TITLE:"Guardant360"', paperMatch: "Guardant360",
    technologies: ["cgp"],
  },
  {
    id: "tempus-xt", name: "Tempus xT", vendor: "Tempus AI", vendorId: "tempus", category: C.gen, segment: S.cgp,
    summary: "A sequencing panel and the interpretation platform Tempus reports it through, sold alongside its real-world data and trial-matching products.",
    url: "https://www.tempus.com/", pageMatch: "Tempus",
    fda: { endpoint: "510k", search: 'applicant:"Tempus AI"', applicant: "Tempus" },
    paperQuery: 'TITLE:"tempus xT"', paperMatch: "Tempus",
    technologies: ["cgp", "variant-knowledgebases"],
  },
  {
    id: "mi-cancer-seek", name: "Caris Molecular Intelligence and MI Cancer Seek", vendor: "Caris Life Sciences", vendorId: "caris", category: C.gen, segment: S.cgp,
    summary: "Caris's approved whole-exome and whole-transcriptome profiling test, with the reporting layer that turns it into treatment options.",
    url: "https://www.carislifesciences.com/", pageMatch: "Caris",
    fda: { endpoint: "pma", search: 'applicant:"Caris"', applicant: "Caris" },
    paperQuery: 'TITLE:"Caris molecular intelligence"', paperMatch: "Caris",
    technologies: ["cgp", "rna-seq"],
  },
  {
    id: "msk-impact", name: "MSK-IMPACT", vendor: "Memorial Sloan Kettering Cancer Center", vendorId: "mskcc", category: C.gen, segment: S.cgp,
    summary: "A hospital's own targeted sequencing test and its analysis pipeline, authorised in the United States and the source of one of the largest public clinical sequencing cohorts.",
    url: "https://www.mskcc.org/msk-impact", pageMatch: "MSK-IMPACT",
    fda: { endpoint: "510k", search: 'device_name:"IMPACT"', applicant: "Memorial" },
    paperQuery: 'TITLE:"MSK-IMPACT"', paperMatch: "MSK-IMPACT",
    technologies: ["cgp", "wes-wgs"],
  },
  {
    id: "oncomine-dx-target-test", name: "Oncomine Dx Target Test", vendor: "Thermo Fisher Scientific", vendorId: "thermo-fisher", category: C.gen, segment: S.cgp,
    summary: "An approved targeted sequencing test with companion diagnostic claims, run on the Ion Torrent platform in hospital laboratories rather than sent away.",
    url: "https://www.thermofisher.com/uk/en/home/clinical/diagnostic-testing/condition-disease-diagnostics/oncology-diagnostics.html", pageMatch: "Oncomine",
    fda: { endpoint: "pma", search: 'trade_name:"Oncomine"', device: "Oncomine" },
    technologies: ["cgp"],
  },
  {
    id: "trusight-oncology-500", name: "TruSight Oncology 500", vendor: "Illumina", vendorId: "illumina", category: C.gen, segment: S.cgp,
    summary: "A large sequencing panel sold as a kit with its own analysis software, so a laboratory can run comprehensive profiling itself.",
    url: "https://www.illumina.com/products/by-brand/trusight-oncology.html", pageMatch: "TruSight Oncology",
    technologies: ["cgp", "ngs-bioinformatics-software"],
  },
  {
    id: "dragen", name: "DRAGEN", vendor: "Illumina", vendorId: "illumina", category: C.gen, segment: S.calling,
    summary: "Hardware-accelerated secondary analysis: alignment and variant calling on a field-programmable gate array, which is how many clinical laboratories keep up with their sequencers.",
    url: "https://www.illumina.com/", pageMatch: "DRAGEN",
    paperQuery: 'TITLE:"DRAGEN" AND (variant OR genome OR sequencing)', paperMatch: "DRAGEN",
    technologies: ["ngs-bioinformatics-software", "wes-wgs"],
    openSourceId: "gatk",
  },
  {
    id: "sentieon", name: "Sentieon", vendor: "Sentieon", category: C.research, segment: S.calling,
    summary: "Reimplementations of the standard variant calling pipelines, including the somatic ones, engineered to give the same answers much faster on ordinary hardware.",
    url: "https://www.sentieon.com/", pageMatch: "Sentieon",
    paperQuery: 'TITLE:"Sentieon"', paperMatch: "Sentieon",
    technologies: ["ngs-bioinformatics-software", "wes-wgs"],
    openSourceId: "gatk",
    note: "Excluded from /open-source/ by design as closed-source commercial software. It is here instead, with the peer-reviewed comparisons attached.",
  },
  {
    id: "qci-interpret", name: "QCI Interpret", vendor: "QIAGEN", vendorId: "qiagen", category: C.gen, segment: S.interp,
    summary: "A variant interpretation and reporting platform that classifies findings against curated evidence and produces the clinical report a molecular tumour board reads.",
    url: "https://www.qiagen.com/us/products/digital-insights", pageMatch: "Clinical Insight",
    paperQuery: 'ABSTRACT:"QIAGEN Clinical Insight"', paperMatch: "Clinical Insight",
    technologies: ["variant-knowledgebases", "ngs-bioinformatics-software"],
  },
  {
    id: "sophia-ddm", name: "SOPHiA DDM", vendor: "SOPHiA GENETICS", vendorId: "sophia-genetics", category: C.gen, segment: S.interp,
    summary: "A cloud analysis and interpretation platform hospitals send their sequencing data to, with its own algorithms for variant calling and for scores such as homologous recombination deficiency.",
    url: "https://www.sophiagenetics.com/platform/", pageMatch: "SOPHiA DDM",
    paperQuery: 'TITLE:"SOPHiA DDM"', paperMatch: "SOPHiA DDM",
    technologies: ["ngs-bioinformatics-software", "hrd-genomic-scar-scores"],
  },
  {
    id: "congenica", name: "Congenica", vendor: "Congenica", category: C.gen, segment: S.interp,
    summary: "A clinical genomic interpretation platform that came out of the Sanger Institute and is used in national sequencing services.",
    url: "https://congenica.com/", pageMatch: "Congenica",
    paperQuery: 'ABSTRACT:"Congenica"', paperMatch: "Congenica",
    technologies: ["ngs-bioinformatics-software"],
  },
  {
    id: "fabric-genomics", name: "Fabric Genomics", vendor: "Fabric Genomics", category: C.gen, segment: S.interp,
    summary: "An interpretation platform with its own prioritisation algorithms, sold to laboratories running clinical sequencing at scale.",
    url: "https://fabricgenomics.com/", pageMatch: "Fabric",
    paperQuery: 'ABSTRACT:"Fabric Genomics"', paperMatch: "Fabric Genomics",
    technologies: ["ngs-bioinformatics-software"],
  },
  {
    id: "franklin-genoox", name: "Franklin", vendor: "Genoox", category: C.gen, segment: S.interp,
    summary: "A variant interpretation platform with a community layer, free at the point of use for individual curators and sold to laboratories.",
    url: "https://www.genoox.com/", pageMatch: "Franklin",
    paperQuery: 'ABSTRACT:"Genoox"', paperMatch: "Genoox",
    technologies: ["variant-knowledgebases"],
  },
  {
    id: "varsome-clinical", name: "VarSome Clinical", vendor: "Saphetor", category: C.gen, segment: S.interp,
    summary: "A variant search engine and clinical interpretation platform, widely used in its free form and sold as a regulated product for diagnostics.",
    url: "https://varsome.com/", pageMatch: "VarSome",
    paperQuery: 'TITLE:"VarSome"', paperMatch: "VarSome",
    technologies: ["variant-knowledgebases"],
  },
  {
    id: "mastermind", name: "Mastermind", vendor: "Genomenon", category: C.gen, segment: S.interp,
    summary: "A search engine over the genomic literature that returns the papers naming a given variant, used as the evidence step in variant classification.",
    url: "https://www.genomenon.com/", pageMatch: "Mastermind",
    paperQuery: 'ABSTRACT:"Genomenon"', paperMatch: "Genomenon",
    technologies: ["variant-knowledgebases"],
  },
  {
    id: "varseq", name: "VarSeq", vendor: "Golden Helix", category: C.gen, segment: S.interp,
    summary: "Desktop software for annotating, filtering and reporting variants, used by laboratories that prefer to keep the analysis in house.",
    url: "https://www.goldenhelix.com/", pageMatch: "VarSeq",
    paperQuery: 'ABSTRACT:"VarSeq"', paperMatch: "VarSeq",
    technologies: ["ngs-bioinformatics-software"],
  },
  {
    id: "pieriandx-cgw", name: "PierianDx Clinical Genomicist Workspace", vendor: "Velsera", vendorId: "velsera", category: C.gen, segment: S.interp,
    summary: "A case management and sign-out environment for molecular pathology, tracking a tumour case from sequencing run to signed report.",
    url: "https://www.velsera.com/", pageMatch: "Velsera",
    paperQuery: 'ABSTRACT:"PierianDx"', paperMatch: "PierianDx",
    technologies: ["ngs-bioinformatics-software", "variant-knowledgebases"],
  },
  {
    id: "dnanexus", name: "DNAnexus", vendor: "DNAnexus", vendorId: "dnanexus", category: C.gen, segment: S.calling,
    summary: "A cloud platform for running and sharing genomic pipelines under the controls a clinical or biobank setting needs.",
    url: "https://www.dnanexus.com/", pageMatch: "DNAnexus",
    paperQuery: 'ABSTRACT:"DNAnexus"', paperMatch: "DNAnexus",
    technologies: ["genomics-cloud-platforms"],
  },
  {
    id: "emedgene", name: "Emedgene", vendor: "Illumina", vendorId: "illumina", category: C.gen, segment: S.interp,
    summary: "An interpretation platform that automates the first pass of variant prioritisation and drafts the evidence behind each call.",
    url: "https://emedgene.com/", pageMatch: "Emedgene",
    paperQuery: 'ABSTRACT:"Emedgene"', paperMatch: "Emedgene",
    technologies: ["ngs-bioinformatics-software"],
  },
  {
    id: "cosmic", name: "COSMIC", vendor: "Wellcome Sanger Institute", category: C.gen, segment: S.interp,
    summary: "The Catalogue of Somatic Mutations in Cancer: the reference list of what has been seen mutated in tumours, free for academic use and licensed for everything else.",
    url: "https://cancer.sanger.ac.uk/cosmic", pageMatch: "COSMIC",
    paperQuery: 'ABSTRACT:"Catalogue of Somatic Mutations in Cancer"', paperMatch: "Catalogue of Somatic Mutations",
    technologies: ["variant-knowledgebases"],
    note: "Excluded from /open-source/ by design because the data are under a commercial licence for non-academic use and no code is published.",
  },

  // ─── Trial matching, trial conduct and registries ──────────────────────────────────────────────────────────────
  {
    id: "clinicaltrials-gov", name: "ClinicalTrials.gov", vendor: "US National Library of Medicine", category: C.trial, segment: S.registry,
    summary: "The public registry of clinical studies and the API almost every trial-matching product in oncology is built on top of.",
    url: "https://clinicaltrials.gov/", pageMatch: "ClinicalTrials.gov",
    paperQuery: 'TITLE:"ClinicalTrials.gov"', paperMatch: "ClinicalTrials.gov",
    technologies: ["clinical-trial-software"],
  },
  {
    id: "who-ictrp", name: "WHO ICTRP Search Portal", vendor: "World Health Organization", category: C.trial, segment: S.registry,
    summary: "The search portal that federates the national trial registries, so a study registered outside the United States can still be found.",
    url: "https://trialsearch.who.int/", pageMatch: "ICTRP",
    paperQuery: 'TITLE:"ICTRP"', paperMatch: "ICTRP",
    technologies: ["clinical-trial-software"],
  },
  {
    id: "euclinicaltrials",
    listings: [{ body: "European Medicines Agency", label: "The agency's own page for the system", url: "https://www.ema.europa.eu/en/human-regulatory-overview/research-and-development/clinical-trials-human-medicines/clinical-trials-information-system", match: "Clinical Trials Information System" }],
    name: "Clinical Trials Information System (CTIS)", vendor: "European Medicines Agency", vendorId: "ema", category: C.trial, segment: S.registry,
    summary: "The European Union's single system for applying to run a trial and for publishing it, which replaced the old national applications and the EudraCT register.",
    url: "https://euclinicaltrials.eu/", pageMatch: "Clinical Trials",
    technologies: ["clinical-trial-software"],
  },
  {
    id: "isrctn",
    listings: [{ body: "World Health Organization", label: "Listed as a primary registry in the WHO registry network", url: "https://www.who.int/clinical-trials-registry-platform/network/primary-registries", match: "ISRCTN" }],
    name: "ISRCTN registry", vendor: "BMC (Springer Nature)", category: C.trial, segment: S.registry,
    summary: "A primary registry recognised by the World Health Organization, used by many United Kingdom trials.",
    url: "https://www.isrctn.com/", pageMatch: "ISRCTN",
    technologies: ["clinical-trial-software"],
  },
  {
    id: "be-part-of-research", name: "Be Part of Research", vendor: "National Institute for Health and Care Research", category: C.trial, segment: S.matching,
    summary: "The United Kingdom's public service for finding a study to take part in, searchable by condition and area.",
    url: "https://bepartofresearch.nihr.ac.uk/", pageMatch: "Be Part of Research",
    technologies: ["clinical-trial-software"],
  },
  {
    id: "massive-bio", name: "Massive Bio", vendor: "Massive Bio", vendorId: "massive-bio", category: C.trial, segment: S.matching,
    summary: "A trial matching service for patients and their doctors, combining an algorithm over the public registry with a human team that works the case.",
    url: "https://massivebio.com/", pageMatch: "Massive Bio",
    technologies: ["ai-trial-matching"],
  },
  {
    id: "leal-health", name: "Leal Health", vendor: "Leal Health", category: C.trial, segment: S.matching,
    summary: "A patient-facing trial matching service that asks about the diagnosis and treatment history and returns studies that fit.",
    url: "https://leal.health/", pageMatch: "Leal",
    technologies: ["ai-trial-matching"],
  },
  {
    id: "carebox", name: "Carebox Connect", vendor: "Carebox", category: C.trial, segment: S.matching,
    summary: "Trial matching infrastructure sold to advocacy groups and sponsors, with a structured version of the registry's eligibility criteria underneath.",
    url: "https://www.careboxhealth.com/", pageMatch: "Carebox",
    technologies: ["ai-trial-matching"],
  },
  {
    id: "antidote-match", name: "Antidote Match", vendor: "Antidote", vendorId: "antidote", category: C.trial, segment: S.matching,
    summary: "A matching engine embedded in patient advocacy websites, turning the registry's free text into questions a person can answer.",
    url: "https://www.antidote.me/", pageMatch: "Antidote",
    technologies: ["ai-trial-matching"],
  },
  {
    id: "paradigm-trials", name: "Paradigm", vendor: "Paradigm Health", category: C.trial, segment: S.matching,
    summary: "A trial access platform that works from the health system's own records to find eligible patients where they are already being treated.",
    url: "https://www.paradigm.inc/", pageMatch: "Paradigm",
    technologies: ["ai-trial-matching"],
  },
  {
    id: "unlearn-ai", name: "Unlearn.AI", vendor: "Unlearn.AI", category: C.trial, segment: S.conduct,
    summary: "Digital twin models of trial participants, used to shrink the control arm of a randomised study.",
    url: "https://unlearn.ai/", pageMatch: "Unlearn",
    technologies: ["clinical-trial-software"],
  },
  {
    id: "medidata-rave", name: "Medidata Rave", vendor: "Medidata", vendorId: "medidata", category: C.trial, segment: S.conduct,
    summary: "The electronic data capture system a large share of oncology trials are run in, with the randomisation and supply modules around it.",
    url: "https://www.medidata.com/en/clinical-trial-products/clinical-data-management/", pageMatch: "Medidata",
    technologies: ["clinical-trial-software"],
  },
  {
    id: "veeva-vault-ctms", name: "Veeva Vault CTMS", vendor: "Veeva Systems", vendorId: "veeva-systems", category: C.trial, segment: S.conduct,
    summary: "Trial management software: sites, monitoring visits, documents and the audit trail a sponsor has to show a regulator.",
    url: "https://www.veeva.com/products/vault-ctms/", pageMatch: "CTMS",
    technologies: ["clinical-trial-software"],
  },
  {
    id: "castor-edc", name: "Castor EDC", vendor: "Castor", category: C.trial, segment: S.conduct,
    summary: "Data capture built for investigator-led studies, sold on speed of setup rather than on the weight of a full sponsor suite.",
    url: "https://www.castoredc.com/", pageMatch: "Castor",
    technologies: ["clinical-trial-software"],
  },
  {
    id: "redcap", name: "REDCap", vendor: "Vanderbilt University", category: C.trial, segment: S.conduct,
    summary: "The data capture system most academic oncology studies actually run on, free to institutions in a consortium but not open source.",
    url: "https://projectredcap.org/", pageMatch: "REDCap",
    paperQuery: 'TITLE:"REDCap"', paperMatch: "REDCap",
    technologies: ["clinical-trial-software"],
    note: "Excluded from /open-source/ by design because the source is available to consortium members only under a licence agreement.",
  },
  {
    id: "citeline", name: "Citeline (Trialtrove and TrialScope)", vendor: "Citeline", category: C.trial, segment: S.conduct,
    summary: "Commercial trial intelligence and disclosure compliance tools, the paid view of the same registries the public ones publish.",
    url: "https://www.citeline.com/", pageMatch: "Citeline",
    technologies: ["clinical-trial-software"],
  },
  {
    id: "iqvia", name: "IQVIA clinical technology", vendor: "IQVIA", vendorId: "iqvia", category: C.trial, segment: S.conduct,
    summary: "The trial technology and data arm of the largest clinical research organisation, from site selection to the data platform a study runs on.",
    url: "https://www.iqvia.com/", pageMatch: "IQVIA",
    technologies: ["clinical-trial-software"],
  },
  {
    id: "cnext", name: "CNExT", vendor: "C/NET Solutions", category: C.trial, segment: S.cancerReg,
    summary: "Cancer registry software used by hospital registrars to abstract, code and submit cases to state and national registries.",
    url: "https://askcnet.org/", pageMatch: "CNExT",
    technologies: ["clinical-trial-software"],
  },
  {
    id: "ncdb",
    listings: [{ body: "American College of Surgeons", label: "The college's own page for submitting data to the registry", url: "https://www.facs.org/quality-programs/cancer-programs/national-cancer-database/ncdb-call-for-data/", match: "National Cancer Database" }],
    name: "National Cancer Database", vendor: "American College of Surgeons", category: C.trial, segment: S.cancerReg,
    summary: "The hospital-based registry that collects most newly diagnosed cancers in the United States, and the reporting tools accredited programmes use against it.",
    url: "https://www.facs.org/quality-programs/cancer-programs/national-cancer-database/", pageMatch: "National Cancer Database",
  },
  {
    id: "flatiron-health", name: "Flatiron Health real-world data", vendor: "Flatiron Health", vendorId: "flatiron-health", category: C.trial, segment: S.rwd,
    summary: "A de-identified oncology database assembled from the electronic records of the practices Flatiron sells software to, used for external control arms and regulatory submissions.",
    url: "https://flatiron.com/", pageMatch: "Flatiron",
    paperQuery: 'TITLE:"Flatiron Health"', paperMatch: "Flatiron",
    technologies: ["clinical-trial-software"],
  },
  {
    id: "concertai", name: "ConcertAI", vendor: "ConcertAI", vendorId: "concertai", category: C.trial, segment: S.rwd,
    summary: "Oncology real-world data and trial acceleration software, sold to sponsors and to the practices whose data it curates.",
    url: "https://www.concertai.com/", pageMatch: "ConcertAI",
    paperQuery: 'ABSTRACT:"ConcertAI"', paperMatch: "ConcertAI",
    technologies: ["clinical-trial-software"],
  },
  {
    id: "komodo-health", name: "Komodo Health", vendor: "Komodo Health", vendorId: "komodo-health", category: C.trial, segment: S.rwd,
    summary: "A claims-based healthcare map used to study treatment patterns and outcomes across whole populations rather than single practices.",
    url: "https://www.komodohealth.com/", pageMatch: "Komodo",
    technologies: ["clinical-trial-software"],
  },

  // ─── Case review and second opinion: the category the Atlas proposal belongs to ────────────────────────────────
  {
    id: "atlas-onco", name: "Atlas", vendor: "Atlas", category: C.case, segment: S.review,
    summary: "A case review workspace aimed at cancer foundations and their clinical teams, bringing a person's records, reports, imaging and genomic results into one place alongside trial search.",
    url: "https://atlasonco.com/", pageMatch: "Atlas",
    technologies: ["multidisciplinary-tumour-board", "ai-trial-matching"],
    note: "Proposed for OnCo in issue 63 with its own website as the only source. It is recorded here on that footing: the product exists and says what it does, and nothing outside the company was found to support any further claim.",
  },
  {
    id: "xcures", name: "xCures", vendor: "xCures", category: C.case, segment: S.review,
    summary: "A service that gathers a patient's records from every institution that holds them, structures them, and puts the result in front of a virtual tumour board.",
    url: "https://www.xcures.com/", pageMatch: "xCures",
    paperQuery: 'ABSTRACT:"xCures"', paperMatch: "xCures",
    technologies: ["multidisciplinary-tumour-board"],
  },
  {
    id: "cancer-commons", name: "Cancer Commons", vendor: "Cancer Commons", category: C.case, segment: S.review,
    summary: "A non-profit that gives people with advanced cancer a scientist to work their case and a route to expert opinions, free at the point of use.",
    url: "https://www.cancercommons.org/", pageMatch: "Cancer Commons",
    paperQuery: 'ABSTRACT:"Cancer Commons"', paperMatch: "Cancer Commons",
    technologies: ["multidisciplinary-tumour-board"],
    note: "Excluded from /open-source/ by design because it is a service with no open licence on its content and no published code.",
  },
  {
    id: "second-md", name: "2nd.MD", vendor: "2nd.MD (Accolade)", category: C.case, segment: S.review,
    summary: "An employer-purchased second opinion service that puts a specialist on a video consultation after collecting the records and slides.",
    url: "https://www.2nd.md/", pageMatch: "2nd.MD",
    technologies: ["telemedicine-teleoncology"],
  },
  {
    id: "cleveland-clinic-virtual-second-opinion", name: "Cleveland Clinic Virtual Second Opinions", vendor: "Cleveland Clinic", vendorId: "cleveland-clinic", category: C.case, segment: S.review,
    summary: "A hospital's own remote second opinion service: records and imaging are collected, a specialist reviews them and writes an opinion.",
    url: "https://my.clevelandclinic.org/online-services/virtual-second-opinions", pageMatch: "Second Opinion",
    technologies: ["telemedicine-teleoncology"],
  },
  {
    id: "included-health", name: "Included Health expert medical opinion", vendor: "Included Health", category: C.case, segment: S.review,
    summary: "Care navigation and expert opinion bought by employers, with cancer among the conditions it routes and reviews.",
    url: "https://includedhealth.com/", pageMatch: "Included Health",
    technologies: ["telemedicine-teleoncology"],
  },
  {
    id: "belong-life", name: "Belong.Life", vendor: "Belong.Life", vendorId: "belong-life", category: C.case, segment: S.review,
    summary: "A patient application with a navigation and question-answering layer, with trial matching and record collection inside the same app.",
    url: "https://belong.life/", pageMatch: "Belong",
    paperQuery: 'ABSTRACT:"Belong.Life"', paperMatch: "belong.life",
    technologies: ["ai-trial-matching", "telemedicine-teleoncology"],
  },
  {
    id: "perci-health", name: "Perci Health", vendor: "Perci Health", vendorId: "perci-health", category: C.case, segment: S.review,
    summary: "A United Kingdom service giving people living with and beyond cancer video access to specialist nurses, dietitians and other allied professionals.",
    url: "https://percihealth.com/", pageMatch: "Perci",
    technologies: ["telemedicine-teleoncology"],
  },
  {
    id: "color-cancer", name: "Color virtual cancer clinic", vendor: "Color Health", vendorId: "color-health", category: C.case, segment: S.review,
    summary: "A virtual clinic bought by employers and health systems, covering screening prompts, risk assessment and navigation after a diagnosis.",
    url: "https://www.color.com/cancer", pageMatch: "Cancer",
    technologies: ["telemedicine-teleoncology"],
  },

  // ─── Research and analysis tools that are not open source (revisiting the /open-source/ skip list) ─────────────
  {
    id: "cibersortx", name: "CIBERSORT and CIBERSORTx", vendor: "Stanford University", category: C.research, segment: S.tool,
    summary: "Deconvolution of bulk expression data into cell type proportions, the standard way to ask what immune cells were in a tumour sample.",
    url: "https://cibersortx.stanford.edu/", pageMatch: "CIBERSORT",
    paperQuery: 'TITLE:"CIBERSORT"', paperMatch: "CIBERSORT",
    technologies: ["rna-seq"],
    note: "Excluded from /open-source/ by design: a web tool under a non-commercial academic licence with no open source.",
  },
  {
    id: "mixcr", name: "MiXCR", vendor: "MiLaboratories", category: C.research, segment: S.tool,
    summary: "Extraction of T-cell and B-cell receptor repertoires from sequencing data, used to measure clonality in tumours and after cell therapy.",
    url: "https://mixcr.com/", pageMatch: "MiXCR",
    paperQuery: 'TITLE:"MiXCR"', paperMatch: "MiXCR",
    technologies: ["rna-seq"],
    note: "Excluded from /open-source/ by design: the source is available under a custom licence that restricts commercial use.",
  },
  {
    id: "canrisk", name: "CanRisk (BOADICEA)", vendor: "University of Cambridge", category: C.research, segment: S.risk,
    summary: "The risk model behind familial breast and ovarian cancer clinics: it takes family history, genetic test results and risk factors and returns a personal risk over time.",
    url: "https://www.canrisk.org/", pageMatch: "CanRisk",
    paperQuery: 'TITLE:"CanRisk" AND (breast OR ovarian OR BOADICEA)', paperMatch: "canrisk",
    technologies: ["oncology-pharmacogenomics"], cancers: ["breast-cancer"],
    note: "Excluded from /open-source/ by design: free to use under a non-commercial licence, with the code not published.",
  },
  {
    id: "ibis-risk-evaluator", name: "IBIS Risk Evaluator (Tyrer-Cuzick)", vendor: "Queen Mary University of London", category: C.research, segment: S.risk,
    summary: "The other widely used breast cancer risk model, distributed as a free calculator and embedded in several screening programmes.",
    url: "https://ems-trials.org/riskevaluator/", pageMatch: "Risk Evaluator",
    paperQuery: 'TITLE:"Tyrer-Cuzick"', paperMatch: "Tyrer-Cuzick",
    cancers: ["breast-cancer"],
    note: "Excluded from /open-source/ by design: free for non-commercial use, with the code not published.",
  },
  {
    id: "lifex", name: "LIFEx", vendor: "Institut Curie and CEA", category: C.research, segment: S.tool,
    summary: "Radiomic feature extraction from PET, CT and MR images, free to use and widely cited in imaging biomarker work.",
    url: "https://www.lifexsoft.org/", pageMatch: "LIFEx",
    paperQuery: 'TITLE:"LIFEx" AND (radiomic OR PET OR tumour OR tumor)', paperMatch: "LIFEx",
    technologies: ["quantitative-imaging-biomarkers"],
    note: "Excluded from /open-source/ by design: free to use, with the source not published.",
  },
  {
    id: "cancer-genome-interpreter", name: "Cancer Genome Interpreter", vendor: "Barcelona Biomedical Genomics Lab", category: C.research, segment: S.tool,
    summary: "A web service that annotates a tumour's mutations, flags the likely drivers and lists the drugs the evidence connects them to.",
    url: "https://www.cancergenomeinterpreter.org/", pageMatch: "Cancer Genome Interpreter",
    paperQuery: 'TITLE:"Cancer Genome Interpreter"', paperMatch: "Cancer Genome Interpreter",
    technologies: ["variant-knowledgebases"],
    note: "Excluded from /open-source/ by design: the interpreter's own code is not published, although several of its building blocks are.",
  },
  {
    id: "netmhcpan", name: "NetMHCpan", vendor: "Technical University of Denmark", category: C.research, segment: S.tool,
    summary: "Prediction of which peptides bind which HLA molecules, the step every neoantigen pipeline runs before it proposes a vaccine target.",
    url: "https://services.healthtech.dtu.dk/services/NetMHCpan-4.1/", pageMatch: "NetMHCpan",
    paperQuery: 'TITLE:"NetMHCpan"', paperMatch: "NetMHCpan",
    note: "Excluded from /open-source/ by design: an academic licence with the source not open.",
  },
  {
    id: "seer-stat",
    listings: [{ body: "National Cancer Institute", label: "Listed on the SEER programme's own data and software page", url: "https://seer.cancer.gov/data-software/", match: "SEER*Stat" }],
    name: "SEER*Stat", vendor: "National Cancer Institute (NIH)", vendorId: "nci", category: C.research, segment: S.tool,
    summary: "The analysis software for the United States cancer registry data: incidence, survival and prevalence statistics computed from SEER itself.",
    url: "https://seer.cancer.gov/seerstat/", pageMatch: "SEER*Stat",
    paperQuery: 'ABSTRACT:"SEER*Stat"', paperMatch: "seer*stat",
    note: "Excluded from /open-source/ by design: free software from the National Cancer Institute with the source not published.",
  },
];

/** Looked for and deliberately not recorded, with the reason, so the page and the report can say so. */
export const SKIPPED: Array<{ name: string; reason: string }> = [
  { name: "Oracle Health Oncology (Cerner)", reason: "Every Oracle page answered the fetch with a firewall block, so not even the company's own words could be read and cited." },
  { name: "navify Tumor Board and navify Mutation Profiler (Roche)", reason: "Roche's product pages answered the fetch with a block page, so nothing could be quoted or verified." },
  { name: "Mia (Kheiron Medical Technologies)", reason: "The company's site answered the fetch with a block page and no FDA clearance is recorded under its name; nothing could be verified." },
  { name: "Mendel.ai", reason: "The site did not resolve at the time of the fetch." },
  { name: "iQemo", reason: "The site did not resolve at the time of the fetch; the NHS chemotherapy prescribing system could not be verified." },
  { name: "Somerset Cancer Register", reason: "No stable public product page was found that a fetch could cite." },
  { name: "OpenClinica", reason: "Already on /open-source/: its community edition is open source, so it belongs on that map rather than this one." },
  { name: "Syapse", reason: "The site now serves only a notice that it has moved, so no current description could be read." },
  { name: "Deep 6 AI", reason: "The site did not resolve at the time of the fetch." },
  { name: "Fujifilm CAD EYE", reason: "No Fujifilm product page for it returned a page at the time of the fetch." },
  { name: "Elekta METRIQ", reason: "Elekta publishes no current product page for its cancer registry software; only tag and article pages were found." },
  { name: "Kaiku Health", reason: "The product's own site no longer serves a page after the acquisition by Elekta." },
  { name: "Oncotype DX, MammaPrint, Signatera, Galleri, Cologuard, BRACAnalysis CDx", reason: "Laboratory tests whose classifier is proprietary rather than software a reader can obtain or run; the assay approvals belong on the test pages, not on a software map." },
  { name: "Epic Beaker, Clinisys, Sunquest", reason: "General laboratory information systems rather than oncology software; recorded here only as context for the pathology platforms." },
  { name: "IBM Watson for Oncology", reason: "Withdrawn from the market; the evaluations that exist describe a product no one can now buy, so it is left to the literature rather than given a row." },
  { name: "ViewRay MRIdian", reason: "The company wound down in 2024 and its product pages are gone, so nothing current could be fetched." },
  { name: "Open-source projects of every kind", reason: "Out of scope by design: they are mapped in full on /open-source/, which this page links to rather than duplicating." },
];
